TicketReselling/TicketReselling.Presentation/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using TicketReselling.Business.Interfaces;
using AutoMapper;
using TicketReselling.Presentation.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Localization;
using System.Threading.Tasks;

namespace TicketReselling.Presentation.Controllers
{
    public class HomeController : Controller
    {
        IEventService eventService;
        IUserService userService;
        //IMapper mapper;
        private readonly IStringLocalizer<HomeController> _localizer;

        public HomeController(IEventService eventService, IUserService userService, IStringLocalizer<HomeController> localizer)
        {
            this.eventService = eventService;
            this.userService = userService;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var events = eventService.DisplayAllEvents();
            return View(Mapper.Map<List<EventDemostrationModel>>(events));
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = _localizer["This is a resource for reselling of your tickets."];

            return View();
        }

        [Authorize]
        public IActionResult UserInfo()
        {
            var user = userService.GetUserByLogin(User.Identity.Name);
            return View(Mapper.Map<UserModel>(user));
        }

        [Authorize]
        [HttpGet]
        public IActionResult UpdateUserInfo()
        {
            var user = userService.GetUserByLogin(User.Identity.Name);
            return View(Mapper.Map<UserModel>(user));
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateUserInfo(UserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = userService.GetUserByLogin(model.Login);
                if (user != null)
                {
                    userService.Update(Int32.Parse(model.Id), model.Login, model.Password, model.FirstName, model.LastName, model.Address, model.PhoneNumber, model.Localization, 2);
                    return RedirectToAction("Index", "Home");
                }
                else ModelState.AddModelError("", _localizer["Action can't be performed"]);
            }
            return View(model);            
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        public IActionResult Error()
        {
            return View();
        }
        
    }
}

TicketReselling/TicketReselling.Presentation/Controllers/TicketController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using TicketReselling.Business.Interfaces;
using AutoMapper;
using TicketReselling.Presentation.Models;
using System.Linq;

namespace TicketReselling.Presentation.Controllers
{
    public class TicketController : Controller
    {
        IOrderService orderService;
        ITicketService ticketService;

        public TicketController(IOrderService orderService, ITicketService ticketService)
        {
            this.orderService = orderService;
            this.ticketService = ticketService;
        }

        [HttpGet]
        public IActionResult ShowTickets(int id)
        {
            var tickets = Mapper.Map<List<TicketModel>>(ticketService.GetTicketsByEvent(id).Where(t => t.Status == "Selling"));
            return View(tickets);
        }
    }
}

TicketReselling/TicketReselling.Presentation/Views/Home/Contact.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Contact"];
    Layout = "_Layout";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    <strong>@Localizer["Support"]:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>@Localizer["Marketing"]:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TicketReselling/TicketReselling.Presentation/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@model IEnumerable<TicketReselling.Presentation.Models.EventDemostrationModel>
@{
    Layout = "_Layout";
    ViewData["Title"] = Localizer["Future events"];
}

<html>
<body>
    <h3>@Localizer["Future events"]</h3><br />

    <table class="table-condensed table-hover">
        <tbody>
            <tr>
                <th></th>
                <th>@Localizer["Event"]</th>
                <th>@Localizer["Date"]</th>
                <th>@Localizer["City"]</th>
                <th>@Localizer["Venue"]</th>
                <th>@Localizer["Description"]</th>
                <th></th>
            </tr>
            @foreach (var i in Model)
            {
                <tr>
                    <td height="150" valign="middle"><img src=@i.Banner class="img-rounded" width="100" height="100" alt=@i.Name.ToString()></td>
                    <td>@i.Name</td>
                    <td>@i.Date.ToString("dd.MM")</td>
                    <td>@i.CityName</td>
                    <td>@i.VenueName</td>
                    <td>@i.Description</td>
                    <td><a class="btn btn-default btn-xs" asp-controller="Ticket" asp-action="ShowTickets" asp-route-id=@i.Id>@Localizer["Show Tickets"]</a></td>
                </tr>
            }
        </tbody>
    </table>



</body>
</html>

TicketReselling/TicketReselling.Presentation/Views/Home/UpdateUserInfo.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using TicketReselling.Business.Interfaces
@using TicketReselling.Presentation.Models

@inject IViewLocalizer Localizer
@model TicketReselling.Presentation.Models.UserModel
@{
    Layout = "_Layout";
    ViewData["Title"] = Localizer["User"];
}

<html>
<body>
    <h3>@Localizer["Add some info about yourself"]</h3><br />

    <form class="form-horizontal" role="form" asp-anti-forgery="true" method="post" asp-action="UpdateUserInfo" asp-controller="Home">
        <div class="validation" asp-validation-summary="ModelOnly" />
        
        <div class="form-group">
            <div class="col-md-10">
                <input type="hidden" asp-for="Login" value="@Model.Login" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="hidden" asp-for="Password" value="@Model.Password" />
            </div>
        </div>

        <div class="form-group">
            <div><label class="col-md-2 control-label" asp-for="FirstName">@Localizer["First Name"]</label></div>
            <div class="col-md-10">
                <input type="text" asp-for="FirstName" value="@Model.FirstName" />
            </div>
            <span asp-validation-for="FirstName" />
        </div>

       <div class="form-group">
            <div><label class="col-md-2 control-label" asp-for="LastName">@Localizer["Last Name"]</label></div>
            <div class="col-md-10">
                <input type="text" asp-for="LastName" value="@Model.LastName" />
            </div>
            <span asp-validation-for="LastName" />
        </div>

        <div class="form-group">
            <div><label class="col-md-2 control-label" asp-for="PhoneNumber">@Localizer["Phone"]</label></div>
            <div class="col-md-10">
                <input type="text" asp-for="PhoneNumber" value="@Model.PhoneNumber" />
            </div>
            <span asp-validation-for="PhoneNumber" />
        </div>

        <div class="form-group">
            <div><label class="col-md-2 control-label" asp-for="Address">@Localizer["Address"]</label></div>
            <div class="col-md-10">
                <input type="text" asp-for="Address" value="@Model.Address" />
            </div>
            <span asp-validation-for="Address" />
        </div>

        <div class="form-group">
            <div><label class="col-md-2 control-label" asp-for="Localization">@Localizer["Localization:"]</label></div>
            <div class="col-md-10">
                <select id="localization" name="Localization">
                    <option value="en"> en </option>
                    <option value="ru"> ru </option>
                    <option value="be"> be </option>
                </select>
            </div>
            <span asp-validation-for="Localization" />
            <input type="hidden" asp-for="Localization" value="$(" #localization").val();" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="@Localizer["Save"]" />
                <a class="btn btn-default" asp-controller="Home" asp-action="Index">@Localizer["Cancel"]</a>
            </div>
        </div>
    </form>
</body>
</html>

TicketReselling/TicketReselling.Presentation/Views/Home/UserInfo.cshtml
@model TicketReselling.Presentation.Models.UserModel
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization

<h2>@Localizer["My info"]</h2><br />

<div>
    <form method="post">
        <div><b>@Localizer["First Name"]:</b> @Model.FirstName</div><br />
        <div><b>@Localizer["Last Name"]:</b> @Model.LastName</div><br />
        <div><b>@Localizer["Address"]:</b> @Model.Address</div><br />
        <div><b>@Localizer["Phone Number"]:</b> @Model.PhoneNumber</div><br />
        <div><b>@Localizer["Login"]:</b> @Model.Login</div><br />
        <div><b>@Localizer["Localization"]:</b> @Model.Localization</div><br />
    </form>
    <div>
        <p>
            <a class="btn btn-default btn-xs" asp-controller="Home" asp-action="UpdateUserInfo" asp-route-id=@Model.Id>@Localizer["Change"]</a>
        </p>
    </div>

</div>